use serde::{Deserialize, Serialize};

/// Represents content originating from the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemModelContent {
    text: String,
}

/// Represents content originating from the user's prompt or context files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserModelContent {
    text: String,
}

/// Represents content generated by an agent or a previous model turn.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentModelContent {
    author: String,
    text: String,
}

/// An enum that represents a single piece of content in a conversation or prompt
/// sent to a model. It distinguishes between system instructions, user input,
/// and agent responses.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ModelContentItem {
    System(SystemModelContent),
    User(UserModelContent),
    Agent(AgentModelContent),
}

impl ModelContentItem {
    /// A helper function to create a `User` content item.
    pub fn user(text: &str) -> Self {
        ModelContentItem::User(UserModelContent { text: text.into() })
    }
}

impl ToString for ModelContentItem {
    fn to_string(&self) -> String {
        match self {
            /*
            ModelContentItem::System(content) => format!("System: {}", content.text),
            ModelContentItem::User(content) => format!("User: {}", content.text),
            ModelContentItem::Agent(content) => {
                format!("Agent ({}): {}", content.author, content.text)
            }
            */
            ModelContentItem::System(content) => format!("{}", content.text),
            ModelContentItem::User(content) => format!("{}", content.text),
            ModelContentItem::Agent(content) => {
                format!("{}", content.text)
            }
        }
    }
}

/// A type alias for a vector of `ModelContentItem`, representing a full
/// conversation or a multi-part prompt.
pub type ModelContent = Vec<ModelContentItem>;
