//! ## Execution Engine Module
//!
//! This module acts as the "engine" that interprets and executes the Abstract
//! Syntax Tree (AST) generated by the `ast2` module. It is responsible for
//! managing state, handling commands, interacting with the file system, and
//! orchestrating calls to external models.
//!
//! ### Key Components:
//!
//! - **`execute.rs`**: Contains the core execution logic, including the `Worker`
//!   struct and the multi-pass (`pass_1`, `pass_2`) execution strategy.
//! - **`state.rs`**: Defines the state machine for handling asynchronous operations,
//!   primarily through the `State` trait and the `AnchorStatus` enum.
//! - **`content.rs`**: Defines the structure of content that is passed to the
//!   external models.
//! - **`variables.rs`**: Manages variables and configuration available during execution.

mod content;
mod execute;
//mod state;
mod tag_answer;
mod tag_forget;
mod tag_include;
mod tag_repeat;
mod tag_set;
mod tags;
mod utils;

use content::*;
use execute::*;
use tag_answer::*;
use tag_forget::*;
use tag_include::*;
use tag_repeat::*;
use tag_set::*;
use tags::*;
use utils::*;

pub use execute::collect_context;
pub use execute::execute_context;

const REDIRECTED_OUTPUT_PLACEHOLDER : &str = "Context here has been answered but output has been redirected, so do not respond anymore to context above this sentence.\n";
