//! ## Execution Engine Module
//!
//! This module acts as the "engine" that interprets and executes the Abstract
//! Syntax Tree (AST) generated by the `ast2` module. It is responsible for
//! managing state, handling commands, interacting with the file system, and
//! orchestrating calls to external models.
//!
//! ### Key Components:
//!
//! - **`execute.rs`**: Contains the core execution logic, including the `Worker`
//!   struct and the multi-pass (`pass_1`, `pass_2`) execution strategy.
//! - **`state.rs`**: Defines the state machine for handling asynchronous operations,
//!   primarily through the `State` trait and the `AnchorStatus` enum.
//! - **`content.rs`**: Defines the structure of content that is passed to the
//!   external models.
//! - **`variables.rs`**: Manages variables and configuration available during execution.

mod content;
mod execute;
mod state;
mod variables;

use content::*;
use state::*;
use variables::*;

pub use execute::collect_context;
pub use execute::execute_context;
